### ISSUE TITLE
[CMS] CMS Engine with Read-Only Endpoint

### ISSUE THREAD

**Issue by delchev** [eclipse-dirigible/dirigible#4914]
CMS Engine with read-only endpoint exposing the documents by path.
Multi-tenancy to be considered as well.

* Create a folder in the `Documents` perspective - `my-static-site`
* Upload the `index.html`:

```html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="styles.css">
</head>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>

</body>
</html>
```

* Upload the `styles.css`:

```css
body {
  background-color: powderblue;
}
h1 {
  color: blue;
}
p {
  color: red;
}
```

* Access the site at: `http://localhost:8080/services/cms/my-static-site/`
* You should see this:

<img width="340" alt="Image" src="https://github.com/user-attachments/assets/f681fef5-82e5-4195-bd5e-100a6ee7fe8c" />
